version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: invisible_city_flows_db
    restart: always
    environment:
      POSTGRES_USER: icf
      POSTGRES_PASSWORD: icfpassword
      POSTGRES_DB: invisible_city_flows
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
